spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: sql12345

#The SQL dialect makes Hibernate generate better SQL for the chosen database
jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  #JPA setting
  jpa.hibernate.ddl_auto: create
